[book]
authors = ["mfontanini"]
language = "en"
multilingual = false
src = "src"
title = "presenterm documentation"

[preprocessor]

[preprocessor.alerts]

[output]

[output.html]
git-repository-url = "https://github.com/mfontanini/presenterm"
default-theme = "navy"
